# SWC Python Day 1

## This is a second level heading

### This is a third level heading


Emphasize text in **boldface** or *italics*

You can add a link to a [website](https://software-carpentry.org/lessons/)

You can add emojis from [this Github repo](https://gist.github.com/rxaviers/7360908)

😍 😟 😏

$\texttt{Add some latex text and formulae}:$

$\int_{a}^{b} x^{2} \, dx$

$\mu$ = 30 


You can also add images like this one:

![](../../Pictures/swc_blue.png)

![](https://apod.nasa.gov/apod/image/2302/Ngc1850_HubbleOzsarac_960.jpg)

## Code Cells

In [3]:
a = 1

## Variables and Types

In [4]:
weight_kg = 60

In [5]:
print(weight_kg)

60


In [6]:
weight_kg0 = 70
print(weight_kg0)

70


In [7]:
0weight_kg = 90
print(0weight_kg)

SyntaxError: invalid syntax (3379446300.py, line 1)

In [8]:
Weight_kg = 100
print(Weight_kg, weight_kg)

100 60


In [9]:
print('The weight in kilograms is: ', weight_kg)

The weight in kilograms is:  60


In [10]:
print(type(weight_kg))

<class 'int'>


In [11]:
x = 2242.325263738745
print(x)
print(type(x))

2242.325263738745
<class 'float'>


In [12]:
y = 1.65754e+07
print(y)
print(type(y))

16575400.0
<class 'float'>


In [13]:
print(x)

2242.325263738745


In [14]:
print(int(x))

2242


In [15]:
print(type(int(x)))

<class 'int'>


In [16]:
new_x = int(x)
print(x)
print(new_x)

2242.325263738745
2242


In [17]:
phrase = 'My favourite number is 23'
print(phrase)
print(type(phrase))

My favourite number is 23
<class 'str'>


In [18]:
print("... and he said 'waarom niet?'")
print('... and he said "waarom niet?"')

... and he said 'waarom niet?'
... and he said "waarom niet?"


## Loading data in Python

In [19]:
import numpy

In [20]:
help(numpy.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, like=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  

In [21]:
numpy.loadtxt('./data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [22]:
data = numpy.loadtxt('./data/inflammation-01.csv', delimiter=',')

In [23]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [24]:
print(type(data))

<class 'numpy.ndarray'>


In [25]:
print(data.dtype)

float64


In [26]:
print(data.shape)

(60, 40)


In [27]:
dir(data)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [28]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [29]:
print("This is the number of pimples of the first patient on the first day: ", data[0,0])

This is the number of pimples of the first patient on the first day:  0.0


In [30]:
print("The number of pimples of the first patient during the first trial: ", data[0, :])

The number of pimples of the first patient during the first trial:  [ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [31]:
data[ :2, :]

array([[ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
         5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
         4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
         0.],
       [ 0.,  1.,  2.,  1.,  2.,  1.,  3.,  2.,  2.,  6., 10., 11.,  5.,
         9.,  4.,  4.,  7., 16.,  8.,  6., 18.,  4., 12.,  5., 12.,  7.,
        11.,  5., 11.,  3.,  3.,  5.,  4.,  4.,  5.,  5.,  1.,  1.,  0.,
         1.]])

In [32]:
print("This is the number of pimples the last patient experiences in trial #1: ", data[-1, :])

This is the number of pimples the last patient experiences in trial #1:  [ 0.  0.  1.  0.  3.  2.  5.  4.  8.  2.  9.  3.  3. 10. 12.  9. 14. 11.
 13.  8.  6. 18. 11.  9. 13. 11.  8.  5.  5.  2.  8.  5.  3.  5.  4.  1.
  3.  1.  1.  0.]
